---
# vim: set ft=yaml.ansible:
#
- name: MIGRATE VIRTUAL MACHINES
  hosts: localhost
  gather_facts: false
  strategy: linear

  environment:
    LANG: C
    LC_ALL: C
    LIBVIRT_DEFAULT_URI: qemu:///system

  vars_files:
    - "conf/migrate_domains.yml"

  vars:
    migrate_nc_port: "20666"
    letters: [ 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q'  ]

  tasks:

    - name: Main loop
      include_tasks: tasks/migrator_main.yml
      when: not domain.1.skip|d()
      with_subelements:
        - "{{ migrate_domains }}"
        - domains
      loop_control:
        loop_var: domain
        label: "{{ domain.1.name }}"
...
