---
# vim: set ft=yaml.ansible:
- name: "MY ENVIRONMENT"
  hosts: all
  become: no

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Import myenv
      import_role:
        name: myenv
...
