---
# vim: set ft=yaml.ansible:
- name: Apply mysql role
  hosts: all
  become: yes

  tasks:
    - name: Include mysql role
      include_role:
        name: mysql
      when: inventory_hostname in groups['mysql']
...
