---
# vim: set ft=yaml.ansible:
- name: Apply all roles
  hosts: all
  serial: 1
  become: yes

  vars:
    ansible_user: anrunner

  tasks:
    - name: Include base role
      include_role:
        name: common

    - name: Include aux/pyopenssl role
      include_role:
        name: aux/pyopenssl
      when: inventory_hostname in groups['bacula_ca']

    - name: Include kvm role
      include_role:
        name: kvm
      when: inventory_hostname in groups['kvm']

    - name: Include net/quagga role
      include_role:
        name: net/quagga
      when: inventory_hostname in groups['quagga']

    - name: Include bacula-fd role
      include_role:
        name: bacula/bacula-fd
      when: inventory_hostname not in groups['nobacula']

    - name: Include ct/docker role
      include_role:
        name: ct/docker
      when: inventory_hostname in groups['docker']

    - name: Include ct/systemd-nspawn role
      include_role:
        name: ct/systemd-nspawn
      when: inventory_hostname in groups['nspawn']

    - name: Include selinux/web role
      include_role:
        name: selinux/web
      when: inventory_hostname in groups['selinux_web']

    - name: Include web/ftpd role
      include_role:
        name: web/ftpd
      when: inventory_hostname in groups['ftpd']

    - name: Include gitlab-runner role
      include_role:
        name: gitlab-runner
      when: inventory_hostname in groups['runners']

    - name: Include memcached role
      include_role:
        name: memcached
      when: inventory_hostname in groups['memcached']

    - name: Include pcmk role
      include_role:
        name: pcmk
      when: inventory_hostname in groups['pacemaker']

    - name: Include redis role
      include_role:
        name: redis
      when: inventory_hostname in groups['redis']

    - name: Include mysql role
      include_role:
        name: mysql
      when: inventory_hostname in groups['mysql']

    - name: Include selinux/bacula/xtrabackup role
      include_role:
        name: selinux/bacula/xtrabackup
      when:
        - inventory_hostname in groups['mysql']
        - selinux_state != 'disabled'

    - name: Include pg/postgresql role
      include_role:
        name: pg/postgresql
      when: inventory_hostname in groups['postgresql']

    - name: Include pg/pgbouncer role
      include_role:
        name: pg/pgbouncer
      when: inventory_hostname in groups['pgbouncer']

    - name: Include pg/postgresql-wal-archive role
      include_role:
        name: pg/postgresql-wal-archive
      when: inventory_hostname in groups['pg_wal_archive']

    - name: Include pg/postgresql-logging-collector role
      include_role:
        name: pg/postgresql-logging-collector
      when: inventory_hostname in groups['pg_log_collector']

    - name: Include web/nginx role
      include_role:
        name: web/nginx
      when: inventory_hostname in groups['nginx']

    - name: Include web/nodejs role
      include_role:
        name: web/nodejs
      when: >
        inventory_hostname in groups['nodejs'] or
        inventory_hostname in groups['build_runners']

    - name: Include web/php role
      include_role:
        name: web/php
      when: >
        inventory_hostname in groups['php_fpm'] or
        inventory_hostname in groups['httpd'] or
        inventory_hostname in groups['build_runners'] or
        inventory_hostname in groups['unit']

    - name: Include web/httpd role
      include_role:
        name: web/httpd
      when: inventory_hostname in groups['httpd']

    - name: Include web/php-fpm role
      include_role:
        name: web/php-fpm
      when: inventory_hostname in groups['php_fpm']

    - name: Include web/unit role
      include_role:
        name: web/unit
      when: inventory_hostname in groups['unit']

    - name: Include laravel tasks
      include_role:
        name: web/php-fpm
        tasks_from: laravel.yml
      when: inventory_hostname in groups['unit']

    - name: Include unit-devel
      include_role:
        name: web/unit
        tasks_from: packages.yml
      when: inventory_hostname in groups['build_unit']

    - name: Include web/composer role
      include_role:
        name: web/composer
      when: >
        inventory_hostname in groups['build_runners'] or
        inventory_hostname in groups['deploy_runners']

    - name: Include web/bitrix-env role
      include_role:
        name: web/bitrix-env
      when: inventory_hostname in groups['bitrix']

    - name: Include web/vhost role
      include_role:
        name: web/vhost
      when:
        - inventory_hostname in groups['nginx'] or inventory_hostname in groups['bitrix']
        - vhost|d([])|length > 0

    - name: Include mon/icinga2 role
      include_role:
        name: mon/icinga2
      when: inventory_hostname in groups['icinga2']
...
