---
# vim: set ft=yaml.ansible:
- name: Apply base roles
  hosts: all
  strategy: linear

  tasks:
    - name: Import base role
      import_role:
        name: common

    - name: Import system/localfiles role
      import_role:
        name: system/localfiles

    - name: Include bacula/bacula-fd role
      include_role:
        name: bacula/bacula-fd
      when: not bacula_fd_skip|d()

- name: Apply aux/pyopenssl role
  hosts: bacula_ca
  strategy: linear

  tasks:
    - name: Import aux/pyopenssl role
      import_role:
        name: aux/pyopenssl

- name: Apply aux/gitupdate role
  hosts: gitlux
  strategy: linear

  tasks:
    - name: Import aux/gitupdate role
      import_role:
        name: aux/gitupdate

- name: Apply kvm role
  hosts: kvm
  strategy: linear

  tasks:
    - name: Import kvm role
      import_role:
        name: kvm

- name: Apply net/quagga role
  hosts: quagga
  strategy: linear

  tasks:
    - name: Import net/quagga role
      import_role:
        name: net/quagga

- name: Apply ct/docker role
  hosts: docker
  strategy: linear

  tasks:
    - name: Import ct/docker role
      import_role:
        name: ct/docker

- name: Apply ct/systemd-nspawn role
  hosts: nspawn
  strategy: linear

  tasks:
    - name: Import ct/systemd-nspawn role
      import_role:
        name: ct/systemd-nspawn

- name: Apply selinux/web role
  hosts: selinux_web
  strategy: linear

  tasks:
    - name: Import selinux/web role
      import_role:
        name: selinux/web

- name: Apply web/ftpd role
  hosts: ftpd
  strategy: linear

  tasks:
    - name: Import web/ftpd role
      import_role:
        name: web/ftpd

- name: Apply ci/gitlab-runner role
  hosts: runners
  strategy: linear

  tasks:
    - name: Import ci/gitlab-runner role
      import_role:
        name: ci/gitlab-runner

- name: Apply memcached role
  hosts: memcached
  strategy: linear

  tasks:
    - name: Import memcached role
      import_role:
        name: memcached

- name: Apply cluster/pcmk role
  hosts: pacemaker
  strategy: linear

  tasks:
    - name: Import cluster/pcmk role
      import_role:
        name: cluster/pcmk

- name: Apply redis role
  hosts: redis
  strategy: linear

  tasks:
    - name: Import redis role
      import_role:
        name: redis

- name: Apply mysql roles
  hosts: mysql
  strategy: linear

  tasks:
    - name: Import mysql role
      import_role:
        name: mysql

    - name: Include selinux/bacula/xtrabackup role
      include_role:
        name: selinux/bacula/xtrabackup
      when: selinux_state != 'disabled'

- name: Apply pg/postgresql role
  hosts: postgresql
  strategy: linear

  tasks:
    - name: Import pg/postgresql role
      import_role:
        name: pg/postgresql

- name: Apply pg/pgbouncer role
  hosts: pgbouncer
  strategy: linear

  tasks:
    - name: Import pg/pgbouncer role
      import_role:
        name: pg/pgbouncer

- name: Apply pg/postgresql-wal-archive role
  hosts: pg_wal_archive
  strategy: linear

  tasks:
    - name: Import pg/postgresql-wal-archive role
      import_role:
        name: pg/postgresql-wal-archive

- name: Apply pg/postgresql-logging-collector role
  hosts: pg_log_collector
  strategy: linear

  tasks:
    - name: Import pg/postgresql-logging-collector role
      import_role:
        name: pg/postgresql-logging-collector

- name: Apply web/nginx role
  hosts: nginx
  strategy: linear

  tasks:
    - name: Import web/nginx role
      import_role:
        name: web/nginx

- name: Apply web/nodejs role
  hosts: nodejs,build_runners
  strategy: linear

  tasks:
    - name: Import web/nodejs role
      import_role:
        name: web/nodejs

- name: Apply web/php role
  hosts: php_fpm,httpd,build_runners,unit
  strategy: linear

  tasks:
    - name: Import web/php role
      import_role:
        name: web/php

- name: Apply web/httpd role
  hosts: httpd
  strategy: linear

  tasks:
    - name: Import web/httpd role
      import_role:
        name: web/httpd

- name: Apply web/php-fpm role
  hosts: php_fpm
  strategy: linear

  tasks:
    - name: Import web/php-fpm role
      import_role:
        name: web/php-fpm

- name: Apply unit roles
  hosts: unit
  strategy: linear

  tasks:
    - name: Import web/unit role
      import_role:
        name: web/unit

    - name: Include laravel tasks
      include_role:
        name: web/php-fpm
        tasks_from: laravel.yml

- name: Apply unit-devel role
  hosts: build_unit
  strategy: linear

  tasks:
    - name: Include unit-devel
      include_role:
        name: web/unit
        tasks_from: packages.yml

- name: Apply web/composer role
  hosts: build_runners,deploy_runners
  strategy: linear

  tasks:
    - name: Import web/composer role
      import_role:
        name: web/composer

- name: Apply web/bitrix-env role
  hosts: bitrix
  strategy: linear

  tasks:
    - name: Import web/bitrix-env role
      import_role:
        name: web/bitrix-env

- name: Apply web/vhost role
  hosts: nginx,bitrix
  strategy: linear

  tasks:
    - name: Include web/vhost role
      include_role:
        name: web/vhost
      when: vhost|d([])|length > 0

- name: Apply mon/icinga2 role
  hosts: icinga2
  strategy: linear

  tasks:
    - name: Import mon/icinga2 role
      import_role:
        name: mon/icinga2

- name: Apply system/useradd role
  hosts: all
  strategy: linear

  tasks:
    - name: Import system/useradd role
      import_role:
        name: system/useradd
...
