---
- name: "NGINX VIRTUAL HOSTS"
  hosts: all
  become: yes

  tasks:
    - name: Include httpd role
      include_role:
        name: httpd
      when: puffer|d('bzz') == 'httpd'

    - name: Include php-fpm role
      include_role:
        name: php-fpm
      when: puffer|d('bzz') == 'php-fpm'

    - name: Include bitrix-env role
      include_role:
        name: bitrix-env
      when: puffer|d('bzz') == 'bitrix-env'

    - name: Import vhost role
      import_role:
        name: vhost
...
